version: "3"

services:
  mysqldb:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  gestionski-back:
    depends_on:
      - mysqldb
    image: sawssen97/gestionski-devops:latest
    build: ./
    restart: always
    ports:
      - 8089:8089
    environment:
      - MYSQL_HOST = mysqldb
      - MYSQL_PASSWORD=root
      - MYSQL_PORT=3306

    volumes:
      -  .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
