version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db:/var/lib/mysql
  gestionski-backend:
    image: hamzanechi/gestionski-devops:${BUILD_NUMBER}
    depends_on:
      - mysqldb
    networks:
      - mynetwork
    build: ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
    volumes:
      -  .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
    mynetwork:
      driver: bridge

volumes:
  db: