version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  gestionski-backend:
    depends_on:
      - mysqldb
    image: sawssen97/gestionski-devops:latest
    build: ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect

    volumes:
      -  .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db:
