version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  gestionski-backend:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=
      - spring.jpa.show-sql=true