version: '3.8'
services:
  mysqldb:
    image: 'mysql:latest'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: stationSki
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql


  spring-app:
    image: ranianadine/gestionski-devops:1.0
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true&useUnicode=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    ports:
      - "8089:8089"

    depends_on:
      - mysqldb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db: